### ISSUE TITLE
Historical information on the tracker

### ISSUE THREAD

**Issue by dumyan** [okfn/open-budget-survey#93]
Currently clicking on "View historical information" on some country leads the user to a page where they can see the monthly historical progress when documents were made available.

The new API will not do snapshots and also the decision has been made that the tracker would not be updated monthly but twice a year.

Because of this a question arises how to proceed with displaying the historical information. There are three options:

- We can show the monthly progress as we do now up until the 2016 data. The 2016 progress (and future data) will have only one record per year. This is because we won't have any information about the past state when the API is updated.
- We can introduce consistency with the latest changes and show only one record per year and keep on doing that in the following years.
- The third option requires changes on the API side so we can have information about the status of the documents in certain time.

**Comment by pwalsh** [comment]
@dumyan 

great you bring this up. So, we need to take the snapshots ourselves. Rather than introduce a database dependency just for a snapshot every 6 months, I'm thinking we could have a script that takes this snapshot, saves it as a static JSON file on S3 or (even in the *explorer* codebase where we have other data), and use that.

What do you think? Is it a reasonable solution?

**Comment by pwalsh** [comment]
@dumyan please move/merge this into #85 

As I see it we need. And, as well as the snapshot issue, I think your first option is best, meaning, we use the monthly snapshots up til 2016, and *half* yearly for 2016 forward.

**Comment by pwalsh** [comment]
Decision:

- Leave old snapshots "as is"
- Implement this in #85
